{% set name = "perl-getopt-euclid" %}
{% set version = "0.4.6" %}
{% set sha256 = "65713094978ae7b7b8e8842b67d877fbe02c57fba6606757f5a569736ec385e4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BIGPRESH/Getopt-Euclid-0.4.6.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:

  host:
    - perl

  run:
    - perl

test:
  imports:
    - Getopt::Euclid


about:
  home: https://github.com/bigpresh/Getopt-Euclid
  license: perl_5
  summary: 'Executable Uniform Command-Line Interface Descriptions'

